### ISSUE TITLE
Add linux-arm64 platform?

### ISSUE THREAD

**Issue by ats-aschwartz** [GoogleChromeLabs/chrome-for-testing#76] opened 2023-10-26 16:51 UTC
> The current list of supported platforms is:
linux64
mac-arm64
mac-x64
win32
win64

Would it be possible to add linux-arm64 in addition to the linux64 (x86-64) version?

**Comment by thiagowfx** [comment] 2023-10-26 16:57
Duplicate of: https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1#issuecomment-1537823171

**Closed by thiagowfx** 2023-10-26 16:57 UTC
