### ISSUE TITLE
Apple Silicone "This application is not supported on this mac"

### ISSUE THREAD

**Issue by dtoms** [GoogleChromeLabs/chrome-for-testing#32] opened 2023-07-21 16:34 UTC
After installing on my Macbook Pro with Apple M1 Max via
`npx @puppeteer/browsers install chrome@stable`

I am unable to start.  This seems a different error than mentioned in the README.  Is apple silicone supported?
<img width="258" alt="Screenshot 2023-07-21 at 9 30 48 AM" src="https://github.com/GoogleChromeLabs/chrome-for-testing/assets/5245557/16358f0f-d258-4e5d-86fe-3315705fcead">

**Comment by thiagowfx** [comment] 2023-07-23 13:33
Cannot reproduce (M1 Pro):

<img width="1265" alt="image" src="https://github.com/GoogleChromeLabs/chrome-for-testing/assets/2840106/c63f8223-6850-4918-b47e-78050e79f4b7">

**Comment by dtoms** [comment] 2023-07-23 15:38
Interesting, thank you. that does work when launched from the command line.  It did not work for me when launched from finder.  That's not really the important use case but was confusing.  Is that expected? 
<img width="1065" alt="Screenshot 2023-07-23 at 8 37 51 AM" src="https://github.com/GoogleChromeLabs/chrome-for-testing/assets/5245557/96e508d0-e02b-46a9-8f39-2e4db784719c">

**Comment by thiagowfx** [comment] 2023-07-23 16:08
Also cannot reproduce, see screenshot below (you can see I don't get the overlay 🚫 icon).

I'm glad it works for you from the command-line so that it doesn't block you. Not sure why the behavior in Finder is different for both of us though.

<img width="1341" alt="image" src="https://github.com/GoogleChromeLabs/chrome-for-testing/assets/2840106/1086bbca-796e-4ddb-9668-b4b81b6b1f6d">

**Comment by dtoms** [comment] 2023-07-23 16:16
That screenshot was helpful.  Here was some additional blurbs when I launched via the command line.

My arch is arm64, but the install process installed `mac-115.0.5790.102/chrome-mac-x64/` whereas your screenshot shows `chrome-mac-arm64`...


```
daniel.toms@Q9JQNC9X77 ~ % arch                                         
arm64
daniel.toms@Q9JQNC9X77 ~ % npx @puppeteer/browsers install chrome@stable
chrome@115.0.5790.102 /Users/daniel.toms/chrome/mac-115.0.5790.102/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
daniel.toms@Q9JQNC9X77 ~ % cd  /Users/daniel.toms/chrome                
daniel.toms@Q9JQNC9X77 chrome % mac-115.0.5790.102/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
zsh: no such file or directory: mac-115.0.5790.102/chrome-mac-x64/Google
daniel.toms@Q9JQNC9X77 chrome % mac-115.0.5790.102/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/G                       
daniel.toms@Q9JQNC9X77 chrome % "mac-115.0.5790.102/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
[57465:259:0723/083617.892174:ERROR:chrome_browser_main.cc(1036)] The use of Rosetta to run the x64 version of Chromium on Arm is neither tested nor maintained, and unexpected behavior will likely result. Please check that all tools that spawn Chromium are Arm-native.
[57465:259:0723/083621.062646:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
```

**Comment by dtoms** [comment] 2023-07-23 16:19
So it seems like my mac has rosetta running and the installer chooses to install a different architecture.  i don't know if that's something that can/should be fixed, or perhaps, noted somewhere.  or if its just my own environment problem to deal with.  i would suspect others would hit this in the future though.

**Comment by mathiasbynens** [comment] 2023-07-24 07:16
FYI @OrKoN. Is `@puppeteer/browsers` selecting the wrong architecture?

**Comment by OrKoN** [comment] 2023-07-24 07:23
I am not able to reproduce:

```
❯ arch
arm64
❯ npx @puppeteer/browsers install chrome@stable
Downloading chrome r115.0.5790.102 - 121.5 MB [====================] 100% 0.0s
chrome@115.0.5790.102 /Users/alexrudenko/src/pptr-test/chrome/mac_arm-115.0.5790.102/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
```

**Comment by OrKoN** [comment] 2023-07-24 07:33
We rely on Node to detect the platform. What does the `node -e "console.log(require('os').arch())"` return for you? It should be the same as `arch`.

**Comment by dtoms** [comment] 2023-07-24 14:22
Ah, got it.  We use `asdf` and are on an old node version `16.13.1` which does not correctly detect the `arch`.  Switching to `v20.5.0` and its correctly detected and Chrome for Testing works as expected.  You might consider adding a nodejs check to the install, or a note to the FAQ, or perhaps this issue will help future travelers.  Thanks all!  

(not sure the closing protocol here so will leave open)

**Comment by thiagowfx** [comment] 2023-07-24 14:27
@OrKoN Do you want to move the issue to https://github.com/puppeteer/puppeteer before we close this bug, or is would you say it is WAI?

**Comment by dtoms** [comment] 2023-07-24 14:40
for posterity, with asdf
```daniel.toms@Q9JQNC9X77 ~ % asdf local nodejs 16.13.1
daniel.toms@Q9JQNC9X77 ~ % node -e 'console.log(require("os").arch())'                         
x64```

**Comment by thiagowfx** [comment] 2023-07-24 15:15
Since it's working with `nvm`, we can just close this. If more issues come up related to `asdf` then we can reconsider.

**Closed by thiagowfx** 2023-07-24 15:15 UTC
