### ISSUE TITLE
Request linux-arm64 binaries

### ISSUE THREAD

**Issue by fritzo** [GoogleChromeLabs/chrome-for-testing#86] opened 2023-11-21 21:12 UTC
Thanks for publishing chrome for testing binaries!  It would be great to have a linux-arm64 binary as inexpensive arm machines are increasingly available from cloud providers.

**Comment by thiagowfx** [comment] 2023-11-22 00:05
This is a duplicate of https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1

**Closed by thiagowfx** 2023-11-22 00:05 UTC
