### ISSUE TITLE
Erro do chrome driver na mudança de versão.

### ISSUE THREAD

**Issue by Gravina03** [GoogleChromeLabs/chrome-for-testing#69] opened 2023-10-18 14:03 UTC
![image](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/148356181/2fa2711b-8cee-4b55-835d-f695f8a7fb2f)

**Comment by thiagowfx** [comment] 2023-10-21 11:11
This seems to be a chromedriver bug, not a Chrome for Testing one. Could you elaborate? How to reproduce?

**Comment by thiagowfx** [comment] 2023-10-30 10:36
Feel free to reopen the bug if you provide more logs. Closing as there's not enough information.

**Closed by thiagowfx** 2023-10-30 10:36 UTC
