### ISSUE TITLE
Consider including ffmpeg.so for MP4 playback support

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/chrome-for-testing#18] opened 2023-06-13 00:41 UTC

**Comment by mathiasbynens** [comment] 2023-06-13 07:02
I appreciate this report, but it’s not an issue with the code in this repository (which concerns the dashboard and JSON API only). Please file it here instead: https://goo.gle/cftbug

**Comment by guest271314** [comment] 2023-06-13 13:16
Chromium authors banned me from contributing on https://bugs.chromium.org/. I found this repository and posted here. If this is something you want to support you or somebody ese will have to file the feature request/bug. Thanks.

**Comment by mathiasbynens** [comment] 2023-06-13 13:18
Ok, I’ve filed it here: https://bugs.chromium.org/p/chromium/issues/detail?id=1454450 (non-public, sorry)

**Comment by guest271314** [comment] 2023-06-13 13:27
No worries. I read the docs and saw you folks were using Chromium source code. I already knew MP4 playback was/is not supported on Chromium and thought you probably want to include the ffmpeg.so bits sincethis is for testing/automation. Thank, again.

**Comment by JonnyBurger** [comment] 2023-07-12 07:08
We at @remotion-dev would appreciate this too.
There are no binaries for Chrome that have proprietary Codecs except the Thorium fork of Chrome, which raises some eyebrows.

Thanks for filing it internally!

**Comment by thiagowfx** [comment] 2023-09-14 15:06
This has landed here: https://chromium-review.googlesource.com/c/chromium/src/+/4701288

**Comment by JonnyBurger** [comment] 2023-09-14 15:08
Awesome! 👏🏼 Thank you for doing this! 🙌🏼🙌🏼

**Comment by guest271314** [comment] 2023-09-16 04:21
@thiagowfx Doesn't appear to be working on Version 119.0.6008.0 (Official Build) (64-bit).

![Screenshot_2023-09-15_21-14-31](https://github.com/GoogleChromeLabs/chrome-for-testing/assets/4174848/ce294203-8bd6-44d9-88e9-da31be40d543)

**Comment by thiagowfx** [comment] 2023-09-17 14:01
<img width="178" alt="image" src="https://github.com/GoogleChromeLabs/chrome-for-testing/assets/2840106/0981f492-0b5d-4261-93e5-f9d45f6aa18c">

Try with `119.0.6010.0`or later

**Comment by guest271314** [comment] 2023-09-17 14:16
Which one of the URL's prvides the latest (unstable) release?

When fetching Node.js nightly release I can do something like this to get the tip-of-tree (latest) release URL

```
let osArch = 'linux-x64';
let [node_nightly_build] = await (
  await fetch('https://nodejs.org/download/nightly/index.json')
).json();
let { version, files } = node_nightly_build;
let node_nightly_url = `https://nodejs.org/download/nightly/${version}/node-${version}-${osArch}.tar.gz`;
console.log(node_nightly_url);
```

**Comment by guest271314** [comment] 2023-09-17 14:37
Looks like yout script throws an error

```
npm run check 119.0.6010.0
npm WARN cli npm v10.1.0 does not support Node.js v21.0.0-nightly20230916db8217b1bf. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

> check
> node --no-warnings check-version.mjs 119.0.6010.0

Checking downloads for v119.0.6010.0…
node:internal/deps/undici/undici:11600
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11600:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async checkVersion (file:///home/xubuntu/localscripts/chrome-for-testing/check-version.mjs:37:20)
    at async file:///home/xubuntu/localscripts/chrome-for-testing/check-version.mjs:55:1 {
  cause: AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [
      Error: connect ETIMEDOUT 34.104.35.123:443
          at createConnectionError (node:net:1634:14)
          at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
          at listOnTimeout (node:internal/timers:575:11)
          at process.processTimers (node:internal/timers:514:7) {
        errno: -110,
        code: 'ETIMEDOUT',
        syscall: 'connect',
        address: '34.104.35.123',
        port: 443
      },
      Error: connect ENETUNREACH 2600:1900:4110:86f:::443 - Local (:::0)
          at internalConnectMultiple (node:net:1176:40)
          at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
          at listOnTimeout (node:internal/timers:575:11)
          at process.processTimers (node:internal/timers:514:7) {
        errno: -101,
        code: 'ENETUNREACH',
        syscall: 'connect',
        address: '2600:1900:4110:86f::',
        port: 443
      }
    ]
  }
}

Node.js v21.0.0-nightly20230916db8217b1bf
```

**Comment by guest271314** [comment] 2023-09-17 14:40
Looks like yout script throws an error when checking for that version

```
$ npm run check 119.0.6010.0
npm WARN cli npm v10.1.0 does not support Node.js v21.0.0-nightly20230916db8217b1bf. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

> check
> node --no-warnings check-version.mjs 119.0.6010.0

Checking downloads for v119.0.6010.0…
node:internal/deps/undici/undici:11600
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11600:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async checkVersion (file:///home/user/chrome-for-testing/check-version.mjs:37:20)
    at async file:///home/user/chrome-for-testing/check-version.mjs:55:1 {
  cause: AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [
      Error: connect ETIMEDOUT 34.104.35.123:443
          at createConnectionError (node:net:1634:14)
          at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
          at listOnTimeout (node:internal/timers:575:11)
          at process.processTimers (node:internal/timers:514:7) {
        errno: -110,
        code: 'ETIMEDOUT',
        syscall: 'connect',
        address: '34.104.35.123',
        port: 443
      },
      Error: connect ENETUNREACH 2600:1900:4110:86f:::443 - Local (:::0)
          at internalConnectMultiple (node:net:1176:40)
          at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
          at listOnTimeout (node:internal/timers:575:11)
          at process.processTimers (node:internal/timers:514:7) {
        errno: -101,
        code: 'ENETUNREACH',
        syscall: 'connect',
        address: '2600:1900:4110:86f::',
        port: 443
      }
    ]
  }
}

Node.js v21.0.0-nightly20230916db8217b1bf



```

**Comment by guest271314** [comment] 2023-09-17 14:52
Alright, for some reason the latest `npm` is not shipped with Node.js nightly release. After `npm install npm@latest -g` then `npm run check 119.0.6010.0` we stil get the warning 

```
npm WARN cli npm v10.1.0 does not support Node.js v21.0.0-nightly20230916db8217b1bf. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.
```

and then this indicating that version is not available. Where did you get that version?

```
> check
> node --no-warnings check-version.mjs 119.0.6010.0

Checking downloads for v119.0.6010.0…
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/linux64/chrome-linux64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/mac-arm64/chrome-mac-arm64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/mac-x64/chrome-mac-x64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/win32/chrome-win32.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/win64/chrome-win64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/linux64/chromedriver-linux64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/mac-arm64/chromedriver-mac-arm64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/mac-x64/chromedriver-mac-x64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/win32/chromedriver-win32.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/win64/chromedriver-win64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/linux64/chrome-headless-shell-linux64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/mac-arm64/chrome-headless-shell-mac-arm64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/mac-x64/chrome-headless-shell-mac-x64.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/win32/chrome-headless-shell-win32.zip 404
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6010.0/win64/chrome-headless-shell-win64.zip 404
❌ NOT OK

```

**Comment by OrKoN** [comment] 2023-09-18 06:16
@guest271314 it is not released yet. You need to wait for it (or a later) to be released across all platforms or you can build that version from source.

**Comment by OrKoN** [comment] 2023-09-18 06:18
See https://googlechromelabs.github.io/chrome-for-testing/ 119.0.6014.0 is currently an upcoming one, so if it gets released across all platforms, it will be the one you want to use.

**Comment by thiagowfx** [comment] 2023-09-19 01:11
There's an internal issue (https://bugs.chromium.org/p/chromium/issues/detail?id=1484126). I'll update this thread once it's resolved.

**Comment by thiagowfx** [comment] 2023-09-19 21:49
The aforementioned issue is resolved. 119.0.6018.0 is available in Canary. I tested https://file-examples.com/storage/fe9315700c650841d9ee30d/2017/04/file_example_MP4_480_1_5MG.mp4 with it, and the video file is successfully played, whereas with an older version it is not.

**Closed by thiagowfx** 2023-09-19 21:49 UTC

**Comment by mathiasbynens** [comment] 2023-09-20 07:35
🥳 

I can confirm https://shaka-player-demo.appspot.com/support.html now matches between Chrome Canary 119.0.6018.4 and Chrome for Testing 119.0.6018.4, with this being the only diff:

```diff
     "org.w3.clearkey": {
       "persistentState": false
     },
-    "com.widevine.alpha": {
-      "persistentState": true
-    },
+    "com.widevine.alpha": null,
     "com.microsoft.playready": null,
     "com.microsoft.playready.recommendation": null,
     "com.apple.fps.1_0": null,
```

This remaining difference is due to a separate issue, which is being tracked here: #45 + https://crbug.com/1475137
