### ISSUE TITLE
Calling for a media api returns 304 instead of 200

### ISSUE THREAD

**Issue by hamza0867** [GoogleChromeLabs/chrome-for-testing#51] opened 2023-09-05 06:21 UTC
## **Steps to reproduce**

1. Serve an mp4 file through an http server using something like [serve](https://www.npmjs.com/package/serve)
2. Open Chrome for Testing and go to url of the media file (e.g: https://localhost:3000/video.mp4)
3. Notice the video is broken. If you inspect in the dev tools you can notice that the call to the mp4 url returns a 304 instead of 200.
4. Open the same url for the media file in Chrome.
5. Notice the video plays as expected.

## **Expected behaviour**
The Chrome for Testing should return 200 and play the video just like how Chrome behaves

**Comment by mathiasbynens** [comment] 2023-09-05 06:25
This is a duplicate of #18. Rest assured that we’re working towards enabling proprietary codecs in Chrome for Testing — however, this work hasn’t completed yet. The tracking bug for this is [crbug.com/1457118](https://crbug.com/1457118) (non-public, sorry).

**Closed by mathiasbynens** 2023-09-05 06:25 UTC
